<h1>Numpy</h1>

1. Создайте одномерный массив my_array, в котором по порядку все числа до 100, кратные 5

In [67]:
import numpy as np

d = np.arange(0,100,5)
d


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

2. Из полученного массива получить массив с кратными 10 числами

In [68]:
d = np.arange(0,100,10)
d

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

3. Получить двумерный массив с двумя столбцами

In [69]:
mass = np.array([[1,2],[6,8]])
mass

array([[1, 2],
       [6, 8]])

4. Получите набор my_second_array, в котором все элементы меньше предыдущего исходного на 5

In [70]:
my_second_array = []
for i in mass:
    for j in i:
        if j>5:
            my_second_array.append(j)
my_second_array


[6, 8]

5. Соедините массивы, полученные в п. 3.1 и 4.1, горизонтально. Используйте .T для транспонирования матрицы.


In [71]:
mass1 = np.array([[1,2,3], [1,2,3,]])
mass2 = np.array([[5,6,7], [5,6,7]])
sum = np.concatenate((mass1,mass2), axis=1)
sum


array([[1, 2, 3, 5, 6, 7],
       [1, 2, 3, 5, 6, 7]])

6. Разделите 2 и 3 строку на 4 верхних строки my_array. Используйте .T для транспонирования матрицы

In [72]:
selected_rows = mass1[1:3]
top_rows = mass2[:4]
result_matrix = selected_rows[:, np.newaxis] / top_rows
result_matrix

array([[[0.2       , 0.33333333, 0.42857143],
        [0.2       , 0.33333333, 0.42857143]]])

7.Оставить только те значения, которые не изменились после деления

In [73]:
filtered_values = result_matrix[result_matrix == result_matrix.astype(int)]
filtered_values

array([], dtype=float64)

8.Снова получить трехстрочный двумерный массив и поменять местами первую и третью строки

In [74]:
l = np.array([[1,2,3],[4,5,6], [7,8,9]])
print ('Матрица до изменений\n',l)
l[0],l[2] = l[2], l[0]
print ('Матрица после\n',l)



Матрица до изменений
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Матрица после
 [[7 8 9]
 [4 5 6]
 [7 8 9]]


9. Получить среднее, медиану и стандартное отклонение для каждой строки, используя команды np.mean(), np.median(), np.std().


In [75]:
spisok = np.array([[1,2,3,4], [5,6,7,8,], [9,10,11,12]])
for i in spisok:
    mean = np.mean(i)
    median = np.median(i)
    std = np.std(i)
    print ('Stroka', i, '\nmean: ', mean, 'median', median, 'std:', std)



Stroka [1 2 3 4] 
mean:  2.5 median 2.5 std: 1.118033988749895
Stroka [5 6 7 8] 
mean:  6.5 median 6.5 std: 1.118033988749895
Stroka [ 9 10 11 12] 
mean:  10.5 median 10.5 std: 1.118033988749895


10. Сделать нормализацию на максимальное значение вдоль строк, поделив каждый элемент массива на max() вдоль строк.

In [76]:
spisok10 = np.arange(1,13).astype(float).reshape(3,4)
for i in range(len(spisok10)):
    maxValue = np.max(spisok10[i])
    spisok10[i] = spisok10[i] / maxValue
print(spisok10)

[[0.25       0.5        0.75       1.        ]
 [0.625      0.75       0.875      1.        ]
 [0.75       0.83333333 0.91666667 1.        ]]


<h1>Pandas</h1>

2.1 Импортируйте данные из файла “Global Population Trends(2016-2022).csv”. Описание данных смотрите ниже.

In [77]:
import pandas as pd

df = pd.read_csv("Global Population Trends(2016-2022).csv")
df

Country  Year Total Population Urban Population Rural Population  \
0     Afghanistan  2017                -                -                -   
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
...           ...   ...              ...              ...              ...   
1068     Zimbabwe  2017                -                -                -   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
0                    55            63.0      37.342       7.027   
1                    56            63.0      36.927       6.981   
2                    58            64.0      36.466       6.791   
3                    60            63.0      36.051       7.113   
4                     -            62.0      35.842       7.344   
...                 ...             ...         ...         ...   
1068                 38            61.0      32.516       8.266   
1069                 39            61.0      32.074       7.972   
1070                 40            61.0      31.518       8.043   
1071                 41            61.0      31.009       8.132   
1072                  -            59.0      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
0             5.129                  49.4           -  
1             5.002                  47.8         3.0  
2              4.87                  46.3         3.0  
3              4.75                  44.8         3.0  
4             4.643                  43.4         3.0  
...             ...                   ...         ...  
1068          3.706                  39.5           -  
1069          3.659                  38.0         2.0  
1070          3.599                  37.1         2.0  
1071          3.545                  36.6         2.0  
1072          3.491                  35.7         2.0  

[1073 rows x 12 columns]

2.2 Считайте несколько первых записей таблицы (head())

In [78]:
head = df.head(5)
head

Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55            63.0      37.342       7.027          5.129   
1                 56            63.0      36.927       6.981          5.002   
2                 58            64.0      36.466       6.791           4.87   
3                 60            63.0      36.051       7.113           4.75   
4                  -            62.0      35.842       7.344          4.643   

  Infant Mortality Rate Growth Rate  
0                  49.4           -  
1                  47.8         3.0  
2                  46.3         3.0  
3                  44.8         3.0  
4                  43.4         3.0

2.3 Определите размерность данного фрейма (shape())

In [79]:
shape = df.shape
shape

(1073, 12)

2.4 Выведите название заголовков столбцов фрейма (columns)


In [80]:
column_names = df.columns
column_names

Index(['Country', 'Year', 'Total Population', 'Urban Population',
       'Rural Population', 'Population Density', 'Life Expectancy',
       'Birth Rate', 'Death Rate', 'Fertility Rate', 'Infant Mortality Rate',
       'Growth Rate'],
      dtype='object')

2.5 Получите описание всех переменных (полей) (info())


In [81]:
info = df.info
info

<bound method DataFrame.info of           Country  Year Total Population Urban Population Rural Population  \
0     Afghanistan  2017                -                -                -   
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
...           ...   ...              ...              ...              ...   
1068     Zimbabwe  2017                -                -                -   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Ex

2.6 Удалите строки, не содержащие значения в столбце «Total Population» - “-”


In [82]:
drop = df.drop(df[df['Total Population'] == '-'].index, inplace=True)
df

Country  Year Total Population Urban Population Rural Population  \
0     Afghanistan  2017                -                -                -   
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
...           ...   ...              ...              ...              ...   
1068     Zimbabwe  2017                -                -                -   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
0                    55            63.0      37.342       7.027   
1                    56            63.0      36.927       6.981   
2                    58            64.0      36.466       6.791   
3                    60            63.0      36.051       7.113   
4                     -            62.0      35.842       7.344   
...                 ...             ...         ...         ...   
1068                 38            61.0      32.516       8.266   
1069                 39            61.0      32.074       7.972   
1070                 40            61.0      31.518       8.043   
1071                 41            61.0      31.009       8.132   
1072                  -            59.0      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
0             5.129                  49.4           -  
1             5.002                  47.8         3.0  
2              4.87                  46.3         3.0  
3              4.75                  44.8         3.0  
4             4.643                  43.4         3.0  
...             ...                   ...         ...  
1068          3.706                  39.5           -  
1069          3.659                  38.0         2.0  
1070          3.599                  37.1         2.0  
1071          3.545                  36.6         2.0  
1072          3.491                  35.7         2.0  

[1073 rows x 12 columns]

2.7 Получите описательную статистику по переменным (например, max(), min(), describe()

In [93]:
seeMin = df.min()
seeMin

'China'

In [94]:
seeMax = df.max()
seeMax

'Tuvalu'

In [84]:
seeDescribe = df.describe()
seeDescribe

Year   Birth Rate   Death Rate
count  1073.000000  1073.000000  1073.000000
mean   2019.013048    18.801519     7.841907
std       1.410190     9.903449     2.973418
min    2017.000000     0.000000     0.000000
25%    2018.000000    10.620000     6.067000
50%    2019.000000    16.025000     7.396000
75%    2020.000000    25.921000     9.313000
max    2021.000000    46.351000    21.700000

2.8 Выполните сортировку данных по нескольким критериям

In [85]:
totalPopulationSort = df.sort_values(by=['Total Population', 'Birth Rate'],ascending=[True, True])
totalPopulationSort

Country  Year Total Population Urban Population  \
133   British Virgin Islands  2017                -                -   
873              South Korea  2017                -                -   
769              Puerto Rico  2017                -                -   
416                Hong Kong  2017                -                -   
466                    Italy  2017                -                -   
...                      ...   ...              ...              ...   
829               Seychelles  2018           96,762           54,855   
1047                 Vietnam  2021       97,468,029       37,088,534   
830               Seychelles  2019           97,625           55,762   
831               Seychelles  2020           98,462           56,661   
832               Seychelles  2021           99,258           57,542   

     Rural Population Population Density Life Expectancy  Birth Rate  \
133                 -                200            75.0       6.847   
873                 -                527            83.0       7.000   
769                 -                375            79.0       7.300   
416                 -              7,041            85.0       7.600   
466                 -                205            83.0       7.600   
...               ...                ...             ...         ...   
829            41,907                210            73.0      17.100   
1047       60,379,495                  -            74.0      15.008   
830            41,863                212            74.0      16.400   
831            41,801                214            77.0      15.800   
832            41,716                  -            73.0      16.800   

      Death Rate Fertility Rate Infant Mortality Rate Growth Rate  
133        6.143          0.872                  11.3           -  
873        5.600          1.052                   2.8           -  
769        9.222          1.101                     -           -  
416        6.300          1.128                     -           -  
466       10.700           1.32                   2.8           -  
...          ...            ...                   ...         ...  
829        8.400           2.41                  12.5         1.0  
1047       7.317          1.944                  16.4         1.0  
830        8.100           2.36                  12.4         1.0  
831        6.800           2.29                  12.2         1.0  
832        9.300           2.46                  12.0         1.0  

[1073 rows x 12 columns]

2.9 Выведите название страны, которая имеет максимальную численность населения

In [86]:
maxPopulationCountryIndex = df['Total Population'].idxmax() #нашел индекс c макс значением при помощи встроенного метода idхmax()
countryWithMaxPopulation = df.loc[maxPopulationCountryIndex, 'Country']
countryWithMaxPopulation

Country  Year Total Population Urban Population Rural Population  \
832   Seychelles  2021           99,258           57,542           41,716   
831   Seychelles  2020           98,462           56,661           41,801   
830   Seychelles  2019           97,625           55,762           41,863   
1047     Vietnam  2021       97,468,029       37,088,534       60,379,495   
829   Seychelles  2018           96,762           54,855           41,907   
...          ...   ...              ...              ...              ...   
591        Malta  2017                -                -                -   
586         Mali  2017                -                -                -   
581     Maldives  2017                -                -                -   
576     Malaysia  2017                -                -                -   
536      Liberia  2017                -                -                -   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
832                   -            73.0      16.800       9.300   
831                 214            77.0      15.800       6.800   
830                 212            74.0      16.400       8.100   
1047                  -            74.0      15.008       7.317   
829                 210            73.0      17.100       8.400   
...                 ...             ...         ...         ...   
591               1,462            82.0       9.200       7.600   
586                  16            59.0      43.378       9.637   
581               1,575            80.0      16.126       2.784   
576                  97            75.0      16.355       5.132   
536                  50            61.0      33.151       8.954   

     Fertility Rate Infant Mortality Rate Growth Rate  
832            2.46                  12.0         1.0  
831            2.29                  12.2         1.0  
830            2.36                  12.4         1.0  
1047          1.944                  16.4         1.0  
829            2.41                  12.5         1.0  
...             ...                   ...         ...  
591            1.26                   5.6           -  
586           6.251                  67.3           -  
581           1.845                   7.1           -  
576           1.929                   6.9           -  
536           4.396                  62.1           -  

[1073 rows x 12 columns]

2.10 Выведите название страны, которая имеет минимальную численность населения

In [86]:
minPopulationCountryIndex = df['Total Population'].idxmin() #нашел индекс c мин значением при помощи встроенного метода idхmin()
countryWithMinPopulation = df.loc[minPopulationCountryIndex, 'Country']
countryWithMinPopulation

2.11 Экспорт фрейма в MS Excel

In [87]:
df1 = pd.DataFrame(df)
df1.to_excel("Global Population Trends(2016-2022).xlsx", index=False)

ModuleNotFoundError: No module named 'openpyxl'